import Head from "next/head";
import { useState, useEffect } from "react";
import {
  Flex,
  Stack,
  Heading,
  Divider,
  Text,
  Button,
  chakra,
} from "@chakra-ui/react";

// components
import Navbar from "../components/Navbar";

// utils
import { getRandomColor } from "../utils/getRandomColor";

const TitleTransformer = () => {
  const [title, setTitle] = useState(["Internship Program - 1"]);
  const [timer, setTimer] = useState(0);
  const [onRandomColor, setOnRandomColor] = useState(false);

  const isButtonRemoveDisabled = title.length === 1;
  const isButtonAddDisabled = title.length === 5;

  const addTitle = () => {
    if (!isButtonAddDisabled)
      setTitle([...title, `Internship Program - ${title.length + 1}`]);
  };

  const removeTitle = () => {
    if (!isButtonRemoveDisabled)
      setTitle(title.filter((_, i) => i !== title.length - 1));
  };

  const handleButtonColor = () => {
    setOnRandomColor(!onRandomColor);
  };

  useEffect(() => {
    let interval;

    if (onRandomColor) {
      interval = setInterval(() => {
        setTimer((prev) => prev + 1);
      }, 1000);
    } else if (!onRandomColor) {
      clearInterval(interval);
      setTimer(0);
    }

    return () => {
      clearInterval(interval);
    };
  }, [onRandomColor]);

  return (
    <>
      <Head>
        <title>Internship Program | Title Transformer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Flex
        w="100%"
        direction="column"
        minHeight="100vh"
        alignItems="center"
        justifyContent="center"
      >
        <Stack spacing={8}>
          {title &&
            title.map((text, i) => (
              <Heading
                textAlign="center"
                key={i}
                color={getRandomColor(onRandomColor)}
              >
                {text}
              </Heading>
            ))}
          <Stack spacing={3}>
            <Divider />
            <Stack
              direction="row"
              justifyContent="center"
              alignItems="center"
              h="20px"
            >
              <Text>Running for: {timer}s</Text>
              <chakra.div h="20px">
                <Divider orientation="vertical" />
              </chakra.div>
              <Text>Title count: {title.length}</Text>
            </Stack>
            <Divider />
            <Stack direction="row" justifyContent="space-between" spacing={8}>
              <Button onClick={handleButtonColor}>
                {onRandomColor ? "Clear color" : "Randomize Color"}
              </Button>
              <Button onClick={addTitle} disabled={isButtonAddDisabled}>
                Add title
              </Button>
              <Button onClick={removeTitle} disabled={isButtonRemoveDisabled}>
                Remove title
              </Button>
            </Stack>
          </Stack>
        </Stack>
      </Flex>
    </>
  );
};

export default TitleTransformer;
