import Head from "next/head";
import {
  Stack,
  Heading,
  Divider,
  Text,
  Box,
  Button,
  Flex,
} from "@chakra-ui/react";
import { ArrowForwardIcon } from "@chakra-ui/icons";

// components
import Navbar from "../components/Navbar";
import Link from "../components/Link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Internship Program</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Flex minHeight="100vh" alignItems="center" position="static">
        <Stack mx="auto" width="572px" spacing={8}>
          <Heading textAlign="center">Internship Program</Heading>
          <Divider />
          <Flex>
            <Box
              w="270px"
              h="150px"
              padding={5}
              border="1px"
              borderColor="gray.200"
              boxShadow="md"
            >
              <Link href="/change-title">
                <Button colorScheme="black" variant="link" alignItems="center">
                  <Heading fontSize="20px">Title Transformer</Heading>
                  <span className="chakra-button__icon">
                    <ArrowForwardIcon />
                  </span>
                </Button>
              </Link>
              <Text marginTop={4}>A simple title transformation panel</Text>
            </Box>
            <Box
              w="270px"
              h="150px"
              padding={5}
              border="1px"
              borderColor="gray.200"
              boxShadow="md"
              ml={8}
            >
              <Button colorScheme="black" variant="link">
                <Heading fontSize="20px">User Fetcher</Heading>
                <span className="chakra-button__icon">
                  <ArrowForwardIcon />
                </span>
              </Button>
              <Text marginTop={4}>
                A simple API fetching and rendering process
              </Text>
            </Box>
          </Flex>
        </Stack>
      </Flex>
    </div>
  );
}
